//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tic_Tac_Toe_WPF_Remake.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tic_Tac_Toe_WPF_Remake.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap About_1 {
            get {
                object obj = ResourceManager.GetObject("About_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap About_2 {
            get {
                object obj = ResourceManager.GetObject("About_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] LiteNetLib {
            get {
                object obj = ResourceManager.GetObject("LiteNetLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap menubg {
            get {
                object obj = ResourceManager.GetObject("menubg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SmileMoon {
            get {
                object obj = ResourceManager.GetObject("SmileMoon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StartSingleGameBG {
            get {
                object obj = ResourceManager.GetObject("StartSingleGameBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на stun.a-mm.tv:3478
        ///stun.jappix.com:3478
        ///stun.rounds.com:3478
        ///stun.sipnet.net:3478
        ///numb.viagenie.ca:3478
        ///stun.12connect.com:3478
        ///stun.12voip.com:3478
        ///stun.1und1.de:3478
        ///stun.2talk.co.nz:3478
        ///stun.2talk.com:3478
        ///stun.3clogic.com:3478
        ///stun.advfn.com:3478
        ///stun.aeta.com:3478
        ///stun.aeta-audio.com:3478
        ///stun.awt.be:3478
        ///stun.b2b2c.ca:3478
        ///stun.bluesip.net:3478
        ///stun.budgetphone.nl:3478
        ///stun.cablenet-as.net:3478
        ///stun.callwithus.com:3478
        ///stun.cheapvoip.com:3478
        ///stun.cloopen.com:3478
        ///stun.comfi.com: [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Stun_servers {
            get {
                return ResourceManager.GetString("Stun_servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на :WaitForClosing
        ///&gt;nul ping.exe -n  2 127.0.0.1
        ///tasklist|find /i %1&gt;nul &amp;&amp; goto WaitForClosing
        ///
        ///del %1
        ///ren &quot;Upd.tmp&quot; %1
        ///start %1.
        /// </summary>
        public static string upd {
            get {
                return ResourceManager.GetString("upd", resourceCulture);
            }
        }
    }
}
